# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go backend dependencies
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "mcalero11"

  # Web frontend dependencies (Node.js/TypeScript)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "mcalero11"

  # Desktop app frontend dependencies (Node.js/TypeScript)
  - package-ecosystem: "npm"
    directory: "/desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "mcalero11"

  # Desktop app Tauri/Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/desktop/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "mcalero11"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
 